-- DOC-5 — Document categories become a managed per-org entity.
--
-- ADDITIVE ONLY. Nothing is dropped and nothing is narrowed.
-- "HrDocument"."category" (the legacy string) is READ here to backfill and is
-- never written, altered, or dropped: it stays NOT NULL and becomes stale by
-- design (F3, Gary 2026-09-28) — see the schema comment on the column.
-- One taxonomy covers library documents AND FillableForm rows (F7), so the
-- backfill touches every HrDocument row regardless of kind, archived included.
-- See docs/prompts/DOC-5.md and docs/prompts/DOC-5_AUDIT.md.
--
-- DDL generated by `prisma migrate diff --from-config-datasource` against
-- branch dev (br-broad-wave-a6vpjdw0, host ep-late-water-a6k53nv2); seed and
-- backfill block hand-appended (a shape diff cannot generate data).

-- AlterTable
ALTER TABLE "HrDocument" ADD COLUMN     "categoryId" TEXT;

-- CreateTable
CREATE TABLE "HrDocumentCategory" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "colorKey" TEXT NOT NULL DEFAULT 'gray',
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HrDocumentCategory_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "HrDocumentCategory_organizationId_idx" ON "HrDocumentCategory"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "HrDocumentCategory_organizationId_name_key" ON "HrDocumentCategory"("organizationId", "name");

-- CreateIndex
CREATE INDEX "HrDocument_categoryId_idx" ON "HrDocument"("categoryId");

-- AddForeignKey
ALTER TABLE "HrDocument" ADD CONSTRAINT "HrDocument_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "HrDocumentCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HrDocumentCategory" ADD CONSTRAINT "HrDocumentCategory_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- DATA MIGRATION, three steps, all in the same transaction as the DDL above,
-- replayed per environment through `prisma migrate deploy`.
--
-- HrDocumentCategory ids are generated PER BRANCH, so they will NOT match
-- across dev/staging/production. Never paste one across branches
-- (CLAUDE.md § Database Evidence).

-- STEP 1 — starter seed (F1). Idempotent: zero-count guard + ON CONFLICT DO
-- NOTHING (TPL-1a / HR-20 shape). MUST MATCH src/lib/document-categories.ts
-- STARTER_DOCUMENT_CATEGORIES exactly — same five names, same colours, same
-- sortOrder; if you change one, change the other, and say so on the DOC-5 row.
-- Handbook is ORANGE (Gary, 2026-09-28: matches the chip users see today).
-- These are RENAMEABLE, DELETABLE rows an operator can see and change.
INSERT INTO "HrDocumentCategory" ("id", "organizationId", "name", "colorKey", "sortOrder", "createdAt", "updatedAt")
SELECT
    'hdc' || replace(gen_random_uuid()::text, '-', ''),
    o."id",
    s."name",
    s."colorKey",
    s."sortOrder",
    NOW(),
    NOW()
FROM "Organization" o
CROSS JOIN (VALUES
    ('Handbook',      'orange', 0),
    ('Pay Agreement', 'green',  1),
    ('Policy',        'blue',   2),
    ('HR Management', 'purple', 3),
    ('Other',         'gray',   4)
) AS s("name", "colorKey", "sortOrder")
WHERE NOT EXISTS (
    SELECT 1 FROM "HrDocumentCategory" c WHERE c."organizationId" = o."id"
)
ON CONFLICT ("organizationId", "name") DO NOTHING;

-- STEP 2 — any legacy string OUTSIDE the five gets its own row, named exactly,
-- gray, appended after the starters in alphabetical order (F1: no document
-- ends up uncategorized). Every writer has been enum-validated since HR-4, so
-- this is expected to insert nothing; it exists so an unexpected value is
-- carried rather than dropped. ON CONFLICT keeps it idempotent.
INSERT INTO "HrDocumentCategory" ("id", "organizationId", "name", "colorKey", "sortOrder", "createdAt", "updatedAt")
SELECT
    'hdc' || replace(gen_random_uuid()::text, '-', ''),
    u."organizationId",
    u."category",
    'gray',
    4 + ROW_NUMBER() OVER (PARTITION BY u."organizationId" ORDER BY u."category"),
    NOW(),
    NOW()
FROM (
    SELECT DISTINCT d."organizationId", d."category"
    FROM "HrDocument" d
    WHERE d."category" NOT IN ('Handbook', 'PayAgreement', 'Policy', 'HRManagement', 'Other')
) u
ON CONFLICT ("organizationId", "name") DO NOTHING;

-- STEP 3 — backfill categoryId by name, org-scoped. The two enum keys whose
-- label differs are mapped; every other value matches its row by exact name.
-- Only NULL categoryIds are touched, so a re-run changes nothing.
UPDATE "HrDocument" d
SET "categoryId" = c."id"
FROM "HrDocumentCategory" c
WHERE c."organizationId" = d."organizationId"
  AND d."categoryId" IS NULL
  AND c."name" = CASE d."category"
                   WHEN 'PayAgreement' THEN 'Pay Agreement'
                   WHEN 'HRManagement' THEN 'HR Management'
                   ELSE d."category"
                 END;
