-- DOC-6 — Key holder register: a return event against the signed Key Agreement.
--
-- ADDITIVE ONLY. One enum, two columns on "HrDocument" (a NOT NULL boolean
-- with DEFAULT false, so every existing document tracks nothing and no
-- register appears until an admin ticks the box), and one new table. Nothing
-- is dropped, narrowed, renamed or backfilled. No data block.
--
-- "HrReturnEvent" is APPEND-ONLY by application contract (no update or delete
-- route), like "HrSignedRecord", whose issue it answers. Rulings F1-F7, R0-R2
-- (Gary, 2026-09-28): docs/prompts/DOC-6.md and docs/prompts/DOC-6_AUDIT.md.
--
-- Generated by `prisma migrate diff --from-config-datasource` against branch
-- dev (host ep-late-water-a6k53nv2), after a pre-check diff on the unedited
-- schema returned "-- This is an empty migration." Nothing hand-added below.

-- CreateEnum
CREATE TYPE "HrReturnEventType" AS ENUM ('Returned', 'Reissued');

-- AlterTable
ALTER TABLE "HrDocument" ADD COLUMN     "returnItemLabel" TEXT,
ADD COLUMN     "tracksReturn" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "HrReturnEvent" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "hrDocumentId" TEXT NOT NULL,
    "staffMemberId" TEXT NOT NULL,
    "type" "HrReturnEventType" NOT NULL,
    "occurredOn" DATE NOT NULL,
    "note" TEXT,
    "recordedByUserId" TEXT NOT NULL,
    "recordedByName" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "HrReturnEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "HrReturnEvent_organizationId_idx" ON "HrReturnEvent"("organizationId");

-- CreateIndex
CREATE INDEX "HrReturnEvent_hrDocumentId_staffMemberId_createdAt_idx" ON "HrReturnEvent"("hrDocumentId", "staffMemberId", "createdAt");

-- CreateIndex
CREATE INDEX "HrReturnEvent_staffMemberId_idx" ON "HrReturnEvent"("staffMemberId");

-- AddForeignKey
ALTER TABLE "HrReturnEvent" ADD CONSTRAINT "HrReturnEvent_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HrReturnEvent" ADD CONSTRAINT "HrReturnEvent_hrDocumentId_fkey" FOREIGN KEY ("hrDocumentId") REFERENCES "HrDocument"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HrReturnEvent" ADD CONSTRAINT "HrReturnEvent_staffMemberId_fkey" FOREIGN KEY ("staffMemberId") REFERENCES "StaffMember"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
