-- HR-20 — Training categories become a managed per-org entity.
--
-- ADDITIVE ONLY. Nothing is dropped and nothing is narrowed.
-- "TrainingModule"."subject" is NOT read, written, mirrored, or dropped by this
-- migration — Gary's 2026-08-10 ruling on the §8.1 Neon evidence: production
-- subjects are subtitles ("MODULE 3: CLEANING & SANITATION BASICS"), not
-- categories, so there is NO BACKFILL and no seed is minted from `subject`.
-- All existing modules start uncategorized, which is a legal resting state:
-- category is OPTIONAL (R-a). See docs/prompts/2026-08-10_HR-20_SESSION.md and
-- docs/prompts/2026-08-10_TRAINING_AUDIT.md.
--
-- DDL generated by `prisma migrate diff --from-config-datasource` against
-- branch dev (br-broad-wave-a6vpjdw0); seed block hand-appended (a shape diff
-- cannot generate data).

-- AlterTable
ALTER TABLE "TrainingModule" ADD COLUMN     "categoryId" TEXT;

-- CreateTable
CREATE TABLE "TrainingCategory" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "colorKey" TEXT NOT NULL DEFAULT 'gray',
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TrainingCategory_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TrainingCategory_organizationId_idx" ON "TrainingCategory"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "TrainingCategory_organizationId_name_key" ON "TrainingCategory"("organizationId", "name");

-- CreateIndex
-- R-b's unique constraint — condition MET: §8.2 returned ZERO duplicate
-- (trainingModuleId, staffMemberId) pairs on all three branches
-- (dev br-broad-wave, staging br-square-feather, production
-- br-sparkling-block), verified by Gary in the Neon console 2026-08-10.
-- Future re-assignment, if ever built, adds a cycle column (HR-15b shape).
CREATE UNIQUE INDEX "TrainingAssignment_trainingModuleId_staffMemberId_key" ON "TrainingAssignment"("trainingModuleId", "staffMemberId");

-- CreateIndex
CREATE INDEX "TrainingModule_categoryId_idx" ON "TrainingModule"("categoryId");

-- AddForeignKey
ALTER TABLE "TrainingCategory" ADD CONSTRAINT "TrainingCategory_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TrainingModule" ADD CONSTRAINT "TrainingModule_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "TrainingCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- DATA MIGRATION: starter seed ONLY. This migration never reads "subject".
--
-- Runs in the same transaction as the structural half and replays per
-- environment through `prisma migrate deploy`. Idempotent: zero-count guard +
-- ON CONFLICT DO NOTHING (TPL-1a step 2's shape). MUST MATCH
-- src/lib/training-categories.ts STARTER_TRAINING_CATEGORIES exactly — same
-- six names, same colours, same sortOrder; if you change one, change the
-- other, and say so on the HR-20 row.
--
-- These are RENAMEABLE, DELETABLE DEFAULTS offered to the operator (DEBT-59:
-- seeding CATEGORY ROWS is fine; stamping MODULES is not — no module row is
-- touched by anything in this file).
--
-- TrainingCategory ids are generated PER BRANCH, so they will NOT match
-- across dev/staging/production. Never paste one across branches
-- (CLAUDE.md § Database Evidence).
INSERT INTO "TrainingCategory" ("id", "organizationId", "name", "colorKey", "sortOrder", "createdAt", "updatedAt")
SELECT
    'trc' || replace(gen_random_uuid()::text, '-', ''),
    o."id",
    s."name",
    s."colorKey",
    s."sortOrder",
    NOW(),
    NOW()
FROM "Organization" o
CROSS JOIN (VALUES
    ('New Hire Training',   'green',  0),
    ('Manager Training',    'purple', 1),
    ('Procedures Training', 'blue',   2),
    ('Operations Training', 'amber',  3),
    ('Product Training',    'pink',   4),
    ('Smoothie Training',   'orange', 5)
) AS s("name", "colorKey", "sortOrder")
WHERE NOT EXISTS (
    SELECT 1 FROM "TrainingCategory" tc WHERE tc."organizationId" = o."id"
)
ON CONFLICT ("organizationId", "name") DO NOTHING;
